# -*- coding: utf-8 -*-
"""Agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRT-ZygqnSF-3aNLGLignN7YVoGVl-lJ
"""

site = input("URL du site : ")
produit = input("Nom du produit : ")
url_produit = input("URL du produit : ")
infos = input("Informations supplémentaires : ")
marche = input("Marché cible : ")
langue = input("Langue de la vidéo : ")
plateforme = input("Plateforme : ")

brief = {
    "site": site,
    "produit": produit,
    "url_produit": url_produit,
    "infos": infos,
    "marche": marche,
    "langue": langue,
    "plateforme": plateforme
}

print("\nBRIEF DU PRODUIT")
print(brief)

print("\nAgent 0 : prêt à rechercher le produit")
print("Produit :", produit)
print("Site :", site)

def rechercher_site(url):
    print("Je recherche sur :", url)

    informations = {
        "nom": "Produit exemple",
        "description": "Description trouvée sur le site",
        "prix": "49.99",
        "caracteristiques": [
            "Caractéristique 1",
            "Caractéristique 2"
        ]
    }

    return informations

resultat_recherche = rechercher_site(url_produit)

print("\nRESULTAT DE LA RECHERCHE")
print(resultat_recherche)

import requests

url = "https://example.com"

response = requests.get(url)

print(response.status_code)

html = response.text

print(html[:1000])

from bs4 import BeautifulSoup

soup = BeautifulSoup(html, "html.parser")

texte = soup.get_text(" ", strip=True)

print(texte)

import requests
from bs4 import BeautifulSoup

url = "https://www.amazon.com/Word-Search-Kids-Puzzle-Book/dp/1960790196/ref=sr_1_1?crid=1P03SYPRLA26O&dib=eyJ2IjoiMSJ9.f2mm9kKT_BnEGbQTQzAbHMza53Mjlwn-nOln-1I16CVnTIihNCaodE7FtbiCQcNvawxjlIiAgeBGqnsZkYj2llhnpCZw31vadhHjomQfsv-JdKxYz-hhY8Z0VuZ2RyPQpanC65y2yv8WbYeEF3eQSSd3_i4HEfXyZQLhIS-vF-cnXCzEjSRDBG896i9419cqDN4pkqTpLOJOeU2Owv34Xw43PKQpx7RKshwVx2djCHwgwDtCrSC-1RNSASO7pr58kODDitPgBLofeztbNgRhN5o6InR80Zqs3ip_KGr1uaU.LVxY78gNeenSGLWPBqsP0gQJ6wiyLCtXcUHXz_S4Ak0&dib_tag=se&keywords=search+and+find+books+for+kids&qid=1787323147&sprefix=search+and+find+books+for+kids%2Caps%2C2157&sr=8-1"

response = requests.get(url)

print("Statut :", response.status_code)

html = response.text

soup = BeautifulSoup(html, "html.parser")

texte = soup.get_text(" ", strip=True)

print(texte[:5000])

titre = soup.title.get_text(strip=True) if soup.title else ""

print("TITRE :")
print(titre)

titre_produit = soup.find(id="productTitle")

if titre_produit:
    print(titre_produit.get_text(" ", strip=True))
else:
    print("Titre non trouvé")

prompt = construire_prompt(product_data)

print(prompt)

def construire_prompt(product_data):

    prompt = f"""
Tu es un agent de recherche produit.

Analyse les informations suivantes :

{product_data}

Ta mission :
- identifier le nom du produit
- identifier la marque ou l'auteur
- identifier la catégorie
- identifier les caractéristiques
- identifier les bénéfices
- identifier la cible
- identifier le prix
- conserver les sources

Ne rien inventer.

Si une information est absente, retourne null.

Retourne uniquement un JSON valide.
"""

    return prompt

prompt = construire_prompt(product_data)

print(prompt)

product_data = {
    "title": titre_produit.get_text(" ", strip=True) if titre_produit else None,
    "url": url,
    "source": "Amazon",
    "raw_text": texte[:5000]
}

print(product_data)

def construire_prompt(product_data):

    prompt = f"""
Tu es un agent de recherche produit.

Analyse les informations suivantes :

{product_data}

Ta mission :
- identifier le nom du produit
- identifier la marque ou l'auteur
- identifier la catégorie
- identifier les caractéristiques
- identifier les bénéfices
- identifier la cible
- identifier le prix
- conserver les sources

Ne rien inventer.

Si une information est absente, retourne null.

Retourne uniquement un JSON valide.
"""

    return prompt

prompt = construire_prompt(product_data)

print(prompt)

!git --version

!git clone https://github.com/samluxobs/UGC-Factory.git

from google.colab import auth
auth.authenticate_user()

import getpass

token = getpass.getpass("Colle ton token GitHub ici : ")

!git clone https://github.com/samluxobs/UGC-Factory.git

!ls UGC-Factory

!ls -la UGC-Factory

# Commented out IPython magic to ensure Python compatibility.
# %%writefile UGC-Factory/test.py
# print("UGC Factory fonctionne !")

# Commented out IPython magic to ensure Python compatibility.
# %cd UGC-Factory
!git status

!git add test.py

!git add test.py

!git status

!git commit -m "Add test file"

!git config --global user.name "Samluxobs"
!git config --global user.email "3971bs@gmail.com"

!git commit -m "Add test file"

!git push
# Researcher Agent - development
